github - user api
Unorthdox-Developers/peek-backend pull request #2
Opened 2021-08-15 01:59 UTC by vinaynv3

**Implemented GraphQL server using Django graphQL library called graphene (https://graphene-python.org/).**

1.  Subclassed graphene module to create query root for GraphQL server
2.  Implemented GithubAPI module to handle requests from external API (React)
3.  classes in the above GithubAPI module will make the API(restAPI) calls to Github API using the requests(https://docs.python- 
     requests.org/en/master/) module for responses.

2021-08-15 15:17 UTC, saranshvaid8 commented on backend/DataEntry/githubAPI.py
> +import requests # HTTPS library
comments on imports don't look good

2021-08-15 15:23 UTC, saranshvaid8 commented on backend/DataEntry/githubAPI.py
> +    #date formater
casing is not consistent

2021-08-15 15:27 UTC, saranshvaid8 commented on backend/DataEntry/githubAPI.py
> +    # return user data to GraphQL schema
consistent casing on comments

2021-08-15 16:00 UTC, saranshvaid8 requested changes
Please resolve the comments

2021-08-31 04:45 UTC, vinaynv3 commented on backend/DataEntry/githubAPI.py
> +import requests # HTTPS library
re-designing backend from the core, above code base, is not part of current designs.
resolved the issue as closed.

2021-08-31 12:11 UTC, saranshvaid8 approved these changes

2021-09-02 02:33 UTC, merged